In [3]:
import sys

print(sys.executable)

c:\Users\ghote\Documents\Proyectos\analisis-de-datos\.venv\Scripts\python.exe

In [4]:
import pandas as pd

In [5]:
datos = {
    "Fecha": ["01/08/2026", "01/08/2026", "02/08/2026", "02/08/2026", "03/08/2026"],
    "Producto": ["Persiana", "Cortina", "Persiana", "Cortina", "Persiana"],
    "Ciudad": ["Pereira", "Cali", "Pereira", "Bogotá", "Cali"],
    "Cantidad": [3, 2, 5, 4, 2],
    "Precio": [250000, 180000, 250000, 180000, 250000]
}

df = pd.DataFrame(datos)

df

        Fecha  Producto   Ciudad  Cantidad  Precio
0  01/08/2026  Persiana  Pereira         3  250000
1  01/08/2026   Cortina     Cali         2  180000
2  02/08/2026  Persiana  Pereira         5  250000
3  02/08/2026   Cortina   Bogotá         4  180000
4  03/08/2026  Persiana     Cali         2  250000

In [6]:
df.shape

(5, 5)

In [7]:
df.columns

Index(['Fecha', 'Producto', 'Ciudad', 'Cantidad', 'Precio'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fecha     5 non-null      str
 1   Producto  5 non-null      str
 2   Ciudad    5 non-null      str
 3   Cantidad  5 non-null      int64
 4   Precio    5 non-null      int64
dtypes: int64(2), str(3)
memory usage: 332.0 bytes

In [9]:
df["Fecha"] = pd.to_datetime(df["Fecha"], dayfirst=True)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fecha     5 non-null      datetime64[us]
 1   Producto  5 non-null      str
 2   Ciudad    5 non-null      str
 3   Cantidad  5 non-null      int64
 4   Precio    5 non-null      int64
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 332.0 bytes

In [11]:
df["Venta"] = df["Cantidad"] * df["Precio"]

In [12]:
df

       Fecha  Producto   Ciudad  Cantidad  Precio    Venta
0 2026-08-01  Persiana  Pereira         3  250000   750000
1 2026-08-01   Cortina     Cali         2  180000   360000
2 2026-08-02  Persiana  Pereira         5  250000  1250000
3 2026-08-02   Cortina   Bogotá         4  180000   720000
4 2026-08-03  Persiana     Cali         2  250000   500000

In [13]:
df["Venta"].sum()

np.int64(3580000)